### ISSUE TITLE
Jenkins build not successful

### ISSUE THREAD

**Issue by mirkopleli** [Sybit-Education/COVID-Bouncer#22]
![image](https://user-images.githubusercontent.com/29863859/95569843-6ab1bc00-0a26-11eb-95e7-0be76ca4eec2.png)

**Solution:**  
https://stackoverflow.com/questions/43037590/field-browser-doesnt-contain-a-valid-alias-configuration

**The solution seems to work, before that there were two errors during the build.**
https://github.com/Sybit-Education/COVID-Bouncer/commit/b2932e509b4851d37d48ef203a338cfed713817f

**Comment by stritti** [comment]
Builds working fine using Actions of GitHub already: https://github.com/Sybit-Education/COVID-Bouncer/actions
